<a href="https://colab.research.google.com/github/Soham-2112/ML-LAB/blob/main/EXP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.51733351, 0.0930215 ])

In [19]:
np.random.rand(5,5)

array([[0.65164805, 0.51828571, 0.51497122, 0.74710829, 0.97859166],
       [0.82039778, 0.52318244, 0.83810466, 0.51117127, 0.83489727],
       [0.74089852, 0.76015682, 0.29281268, 0.16223043, 0.65905226],
       [0.61762772, 0.79457832, 0.27250995, 0.81831557, 0.52697072],
       [0.05116004, 0.03632745, 0.35251218, 0.08002385, 0.26168391]])

In [20]:
np.random.randn(2)

array([0.34861222, 0.62392398])

In [21]:
np.random.randn(5,5)

array([[ 0.62320154, -0.09468648, -0.67604802,  0.96878361,  0.78184164],
       [ 3.01809499,  0.43568853,  0.13622916,  0.09810127, -1.32185141],
       [ 0.89892011, -1.43994023, -0.40362056,  0.04289123, -1.34971153],
       [-2.26510861, -1.06525512,  1.38551676,  0.36098823,  0.41583129],
       [ 0.39810055, -0.78115176, -1.54541717,  0.11270695, -0.23683363]])

In [22]:
np.random.randint(1,100)

24

In [23]:
np.random.randint(1,100,10)

array([73, 50, 37, 67, 29, 35, 87,  8, 17, 87])

In [25]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

array([29, 43, 24,  0, 36,  3, 42, 31, 13,  4])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr

array([29, 43, 24,  0, 36,  3, 42, 31, 13,  4])

In [30]:
ranarr.max()

np.int64(43)

In [31]:
ranarr.argmax()

np.int64(1)

In [32]:
ranarr.min()

np.int64(0)

In [33]:
ranarr.argmin()

np.int64(3)

In [34]:
arr.shape

(25,)

In [35]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr.reshape(1,25).shape

(1, 25)

In [37]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [38]:
arr.reshape(25,1).shape

(25, 1)

In [39]:
arr.dtype

dtype('int64')